version: '3.8'

services:
  chat2repo:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - GITEE_ACCESS_TOKEN=${GITEE_ACCESS_TOKEN}
      - GITEE_API_BASE=${GITEE_API_BASE}
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
